# Header
menu:
  网站首页: index.html
  这就是我: /about
  我的班级: http://201604ban.bhxx.net
  我的学校: http://www.bhxx.net
  RSS: /atom.xml

# Content
excerpt_link: 更多内容
prev: 上一页
next: 下一页
#reply: 评论
#share: 分享
fancybox: true

# Sidebar
widgets:
- about
- recent_posts
- archive
- category
- tagcloud
- link
- music

# Miscellaneous
google_analytics:
#duoshuo_shortname: flhexo
rss: /atom.xml
#favicon: http://7u2hdm.com1.z0.glb.clouddn.com/favicon.ico
#google_site_verification: NCXVSqxqB-os803-VFMtIEd1SUNJVOIjctCfNYUwD0w
#baidu_site_verification: Nzwx7HuplM
#bing_site_verification: 9E9EA92F7E5327E1FE8A5196D5253664
music: https://whqet.github.io/lovelyGirl/mp3/baby.mp3